# Generated by Django 5.0.1 on 2025-11-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_clip_include_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='include_subtitles',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='subtitle_text',
        ),
    ]
