# Generated by Django 5.0.1 on 2025-11-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_remove_subtitle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='subtitle_text',
            field=models.TextField(blank=True),
        ),
    ]
