# Generated by Django 5.0.1 on 2025-11-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_add_subtitle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='is_published_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='youtube_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
