# Generated by Django 5.0.1 on 2025-11-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_clip_is_published_youtube_clip_youtube_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='moment_index',
            field=models.IntegerField(default=-1),
        ),
    ]
